-- sql/mobility_schema_pg.sql — 이동·동선(Mobility) 모듈 저장소 · PostgreSQL 이식본
-- 대상: PostgreSQL 12+ (팀 ERD 기준 16). 스키마 `mobility` 안에 둔다.
-- 원본: sql/mobility_schema.sql (SQLite · 375줄 · 13표)
-- 결정: claude/2026-09-14_Mobility_저장소전환_결정_v1.md
-- 적재: scripts/load_mobility_db.py (--dsn 추가 필요)
--
-- ── 이식 규칙 (2026-09-14) ────────────────────────────────────────────────
--  ★ 타입을 바꾼 것은 **JSON 컬럼뿐**이다. 나머지는 의미를 그대로 보존했다.
--    동결(9/18)이 가까워, 이식에서 의미를 바꾸면 무엇이 깨졌는지 구분이 안 된다.
--    "더 PG 다운" 선택지는 아래 ⓑⓒⓓ 에 적어 두고 전환 뒤로 미룬다.
--
--  ⓐ TEXT              → text            (PG 는 길이 제한이 없고 varchar 보다 이점이 없다)
--  ⓐ REAL              → double precision (SQLite REAL 은 8바이트다. PG 의 real 은 4바이트라
--                                          좌표·소요값에서 정밀도가 깎인다)
--  ⓐ INTEGER           → integer          (dep_min 최댓값 1650 — 범위 충분)
--  ⓐ INTEGER PRIMARY KEY
--                      → bigint GENERATED **BY DEFAULT** AS IDENTITY
--                        ★ ALWAYS 가 아니다. 적재기가 id 를 직접 넣는 경로가 있어도 막히지 않는다.
--  ⓐ *_json TEXT       → **jsonb**        ← 유일하게 의미가 바뀌는 자리. 아래 ★적재기 영향 참조
--  ⓐ PRAGMA foreign_keys = ON;
--                      → 삭제. PG 는 FK 를 항상 강제한다.
--
--  ⓑ 0/1 플래그(is_spur·has_timetable·crosses_midnight·timetable_available·stage_assumed)를
--     boolean 으로 바꾸지 **않았다.** PG 의 native 선택은 boolean 이지만 적재기와 모든 질의가
--     0/1 을 전제한다. smallint + CHECK (x IN (0,1)) 로 의미를 그대로 둔다. → 동결 이후 항목.
--
--  ⓒ 시각 문자열(fetched_at·observed_at·decided_at·checked_at·built_at·holiday_date)을
--     timestamptz·date 로 올리지 **않았다.** 이유가 정직성이다 —
--     `fetched_at_precision IN ('day','second')` 가 말하듯 **일 정밀도 값이 섞여 있다.**
--     timestamptz 로 올리면 수집일 값에 00:00:00 이 붙어 **초 정밀도처럼 보인다.**
--     근거 등급에 확인 시각을 붙이는 모듈이 시각의 정밀도를 위조하면 안 된다. → 보류(영구일 수 있다).
--
--  ⓓ UNIQUE 의 NULL 취급이 SQLite 와 다르다. 원본 주석이 지적한 결함을 PG 15+ 가 스키마로 막을 수 있다.
--     ux_timetable 바로 위에 적어 두었다. **기본은 원본과 같은 의미로 두고, 적재 성공을 확인한 뒤 켠다.**
--
--  ★ 적재기 영향 — jsonb 로 바뀐 컬럼 넷:
--    mob_verdict_evidence.value_json · mob_leg_verdict.{reasons,relax,estimate}_json · mob_bus_speed.by_hour_kmh
--    지금은 `json.dumps(...)` 로 문자열을 넣는다. psycopg 는 dict/list 를 그대로 받으려면
--    `psycopg.types.json.Jsonb(...)` 로 감싸야 한다. 문자열을 그대로 넣으면
--    **jsonb 안에 "문자열 하나"가 들어가 버린다**(형이 통과하므로 조용히 잘못된다).
--
-- ── 원본 스키마가 지키는 것 (지우지 말 것) ────────────────────────────────
-- 아래는 전부 **실제로 틀렸던 것을 고친 자리**다.
-- 컬럼 타입 하나를 되돌리면 그때 그 버그가 그대로 돌아온다.
--
--  ① 시각은 전부 **분 단위 integer**다. time·text 로 잡지 않는다.
--     지하철 dep_time 에 24:50, 버스 막차에 27:30 이 들어간다.
--     00:50 으로 되돌리면 그 행이 하루의 가장 이른 시각이 되어 첫차·막차가 둘 다 뒤집힌다(C4).
--  ② 출발 시각은 **NULL 을 허용**한다. 시·종착역은 출발이 없다.
--     0 으로 채우면 막차 판정이 뒤집히고 24 로 채우면 가짜 막차가 생긴다(2,527행).
--  ③ 방향의 정본은 dir 이 아니라 **행선지**다. 인천2호선·신림선은 같은 dir 에 양 끝이 섞인다.
--  ④ mob_verdict_evidence.source_type 에 CHECK 를 건다 — 카카오 응답('tool_result')을 **스키마로 막는다.**
--  ⑤ 카카오 유래 값은 **컬럼으로 만들지 않는다** — 소요·도보 거리·환승 횟수·정류장·좌표·요금.
--  ⑥ 요일축은 표마다 **값 집합이 다르다.** 시간표 3종 · 혼잡도 3종이지만 세 번째 값이 다르다.
--  ⑦ FK 를 **일부러 안 거는 곳이 둘** 있다. 해당 표에 이유를 적었다.
-- ═════════════════════════════════════════════════════════════════════════

CREATE SCHEMA IF NOT EXISTS mobility;

-- 이 파일은 표 이름을 전부 mobility. 로 한정한다. search_path 에 의존하지 않는다.
-- 적재기·질의 쪽은 `SET search_path TO mobility, public;` 한 줄로 기존 SQL 을 그대로 쓸 수 있다.
-- 표 이름의 mob_ 접두어는 그대로 둔다(전환 결정 §2-②) — 동결까지 나흘이라 이름 정리는 뒤로 미룬다.


-- ════════════════════════════════════════════════════════════════════════
--  A. 참조 데이터 — 재생성 가능. 백업 대상이 아니다.
--     재적재는 이 표들만 비운다(TRUNCATE). 산출 2표(B)는 건드리지 않는다.
-- ════════════════════════════════════════════════════════════════════════

-- A1. 지하철 통합 시간표 (463,326행) ─────────────────────────────────────
--     TAGO + 서울 열린데이터광장(OA-101) 보충 + 지선 접속역 보충.
CREATE TABLE IF NOT EXISTS mobility.mob_timetable (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line                 text    NOT NULL,          -- '02호선' — 열린데이터광장 LINE_NUM 표기로 통일
    station_key          text    NOT NULL,          -- '02호선|강변'
    station_cd           text,                      -- 열린데이터광장 역코드. 못 이은 행은 NULL
    station_nm           text    NOT NULL,
    station_nm_en        text,
    dir                  text    NOT NULL CHECK (dir IN ('U','D')),
                                                    -- ★ 소스가 준 값. 방향의 정본이 아니다(위 ③)
    day_type             text    NOT NULL CHECK (day_type IN ('weekday','saturday','holiday')),
    dep_min              integer,                   -- ★ 분 단위. 24시 이상 가능(1490 = 24:50). NULL = 출발 없음(위 ①②)
    arr_min              integer,
    dest_station_nm      text,                      -- 행선지 — ★ 역명으로 정규화한 값. 조인이 되는 쪽
    dest_station_nm_src  text,                      -- 소스 원표기. 추적용이고 조인에 쓰지 않는다
    orig_station_nm      text,                      -- 시발역(정규화). OA-101 의 SUBWAYSNAME 이 여기다
    orig_station_nm_src  text,
    train_no             text,                      -- OA-101 만 준다. 열차 복원에 쓴다
    express              text,
    source               text    NOT NULL,          -- 'tago_subway' | 'seoul_opendata_OA-101'
    source_station_id    text    NOT NULL,
    fetched_at           text    NOT NULL,          -- 확인 시각. Evidence.observed_at 이 된다 (위 ⓒ)
    fetched_at_precision text    NOT NULL CHECK (fetched_at_precision IN ('day','second'))
);
--  ★ orig_station_nm 이 따로 있는 이유 (2026-09-11)
--    열린데이터광장 OA-101 의 SUBWAYSNAME 은 **행선지가 아니라 시발역**이다.
--    TRAIN_NO 로 열차를 복원해 세면 첫 역 일치 2,079건 · 끝 역 일치 0건이다.
--    행선지로 읽던 동안 2호선 막차 행선지가 101개 조합에서 뒤집혀 있었다
--    (도림천 평일 막차가 '신도림행' → 실제 '까치산행'). 두 필드를 한 컬럼에 섞지 않는다.
--    회귀 검사: consistency_check.py C6.
--  ★ 행선지는 **정규화해서 넣는다.** 원표기 그대로면 52,844행(11%)이 mob_station_coord 와 안 붙는다.
--    정규화 규칙은 line_station_order_v1.json 의 dest_alias 와 같다(괄호 제거, 끝의 '역' 제거).

--  ★★ SQLite 와 PG 의 차이가 드러나는 유일한 자리다(이식 규칙 ⓓ).
--    원본 주석: "SQLite 는 UNIQUE 에서 NULL 을 서로 다른 값으로 본다. dep_min 이 NULL 인 행
--    (시·종착역)은 이 인덱스로 안 걸러지므로 적재 스크립트가 한 번 더 거른다."
--    PG 도 기본 동작은 같다. 다만 **PG 15+ 는 NULLS NOT DISTINCT 로 스키마에서 막을 수 있다** —
--    "문서가 아니라 제약으로 강제한다"는 이 스키마의 방침에 맞는 쪽이다.
--    ★ 지금은 켜지 않는다. 이식과 의미 변경을 같은 날 하지 않는다.
--      전환 적재가 성공한 뒤, 아래 줄로 바꿔 달고 적재를 한 번 더 돌려 거부 행 수를 확인한다.
--      (거부가 생기면 그 행들이 적재기가 따로 거르던 행이다 — 스크립트의 그 분기를 지운다.)
--
--      CREATE UNIQUE INDEX ux_timetable ON mobility.mob_timetable
--          (source, source_station_id, day_type, dir, dep_min, arr_min, dest_station_nm, train_no)
--          NULLS NOT DISTINCT;
CREATE UNIQUE INDEX IF NOT EXISTS ux_timetable
    ON mobility.mob_timetable (source, source_station_id, day_type, dir, dep_min, arr_min, dest_station_nm, train_no);
CREATE INDEX IF NOT EXISTS ix_timetable_lookup
    ON mobility.mob_timetable (line, station_nm, dir, day_type, dep_min);
    --  판정기의 주 질의 — "이 역 이 방향 이 요일에서 t 이후 다음 출발".
CREATE INDEX IF NOT EXISTS ix_timetable_station_key ON mobility.mob_timetable (station_key);
    --  혼잡도·역 목록과 대조할 때. 없으면 소스 간 점검 질의가 전수 스캔이 된다.
CREATE INDEX IF NOT EXISTS ix_timetable_dest
    ON mobility.mob_timetable (line, station_nm, day_type, dest_station_nm);
    --  막차 후보를 행선지로 거를 때.

-- A2. 노선별 역 순서 — 간선 (777) ────────────────────────────────────────
--     "이 열차가 내 목적지를 지나는가"를 푸는 표. 02번 방 막차 판정의 뼈대다.
CREATE TABLE IF NOT EXISTS mobility.mob_line_edge (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line                text    NOT NULL,
    station_a           text    NOT NULL,          -- (a,b) 는 정렬해 넣는다. 무향 간선이다
    station_b           text    NOT NULL,
    edge_source         text    NOT NULL,          -- 'fr_seq' | 'fr_sub' | 'manual:<이유>'
    grade               text    NOT NULL,          -- '확정' | '추정:…' | '근거없음'
    travel_min          double precision,          -- 0.1분 단위. NULL = 근거없음(46/777)
    travel_min_source   text CHECK (travel_min_source IN ('observed','official')),
    travel_min_grade    text CHECK (travel_min_grade IN ('확정','추정')),
    distance_m          integer,                   -- 서울교통공사 공식 역간거리(270개 간선)
    dir_a_to_b          text CHECK (dir_a_to_b IN ('U','D')),  -- a→b 로 달리는 열차의 dir 라벨
    dir_b_to_a          text CHECK (dir_b_to_a IN ('U','D')),
    note                text
);
--  ★ travel_min 은 출처를 반드시 같이 본다.
--    'observed' = 우리가 출발시각 차로 관측한 값. **정차시간이 들어 있다.**
--    'official' = 서울교통공사 역간거리·소요시간표. **주행시간만**이라 평균 0.5분 작다.
--    승객이 겪는 값은 observed 쪽이라 관측이 있으면 관측을 쓰고, 없을 때만 official 로 메운다.
--    250개 구간 대조에서 절대중앙 차이 0.50분, ±1분 이내 100%.
--  ★ grade 가 '근거없음'인 간선을 지나는 경로는 판정도 근거없음으로 낸다.
CREATE UNIQUE INDEX IF NOT EXISTS ux_line_edge ON mobility.mob_line_edge (line, station_a, station_b);
CREATE INDEX IF NOT EXISTS ix_line_edge_a ON mobility.mob_line_edge (line, station_a);
CREATE INDEX IF NOT EXISTS ix_line_edge_b ON mobility.mob_line_edge (line, station_b);

-- A3. 역 좌표 + 노선 내 순서 (793) ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS mobility.mob_station_coord (
    station_key         text    PRIMARY KEY,       -- '01호선|명학'
    line                text    NOT NULL,
    station_nm          text    NOT NULL,
    station_nm_en       text,
    station_cd          text,
    fr_code             text,                      -- 공식 역번호. 노선 순서의 정본이다
    fr_order            integer,                   -- FR_CODE 정렬 순번(노선 안에서)
    is_spur             smallint NOT NULL DEFAULT 0 CHECK (is_spur IN (0,1)),
    has_timetable       smallint NOT NULL DEFAULT 0 CHECK (has_timetable IN (0,1)),
    lat                 double precision,          -- 좌표 미확보 6역은 NULL
    lng                 double precision,
    operator            text,
    source              text,
    fetched_at          text
);
--  ★ 역 순서는 FR_CODE 가 정본이다. 시간표에서 유도한 순서는 틀린다 —
--    열차가 여러 차량기지에서 따로 출발해 min(출발시각)이 같은 열차의 것이 아니다.
--    (3호선 하행에서 대곡 다음이 구파발로 튀고 압구정이 9번째로 올라왔다.) 시간표는 검증용으로만.
CREATE INDEX IF NOT EXISTS ix_station_line_order ON mobility.mob_station_coord (line, fr_order);
CREATE INDEX IF NOT EXISTS ix_station_nm ON mobility.mob_station_coord (station_nm);

-- A4. 환승역 도보 거리 (213쌍 · 74역) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS mobility.mob_transfer_walk (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_nm          text    NOT NULL,
    from_line           text    NOT NULL,
    to_line             text    NOT NULL,
    distance_m          double precision NOT NULL,
    walk_min            double precision NOT NULL, -- 거리 ÷ 우리 실측 1.04 m/s
    grade               text    NOT NULL,          -- distance_m 확정 · walk_min 추정
    checked_at          text    NOT NULL           -- 소스 기준일(2025-12-31)
);
--  ★ 소스의 소요시간(src_min)은 담지 않는다. 소스는 1.2 m/s 환산값인데 우리는 실측 1.04 m/s 를 쓴다.
--    남의 보행속도 가정을 표에 굳히면 나중에 어느 쪽 값인지 구분이 안 된다. 거리만 받아 우리가 나눈다.
--  ★ 서울교통공사 관할 환승만 있다. 코레일·공항철도끼리의 환승은 소스에 없다 → 근거없음.
CREATE UNIQUE INDEX IF NOT EXISTS ux_transfer_walk ON mobility.mob_transfer_walk (station_nm, from_line, to_line);

-- A5. 지하철 혼잡도 (65,169) ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mobility.mob_congestion (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_key         text    NOT NULL,
    station_cd          text,
    station_nm          text    NOT NULL,
    line                text    NOT NULL,
    branch              text,                      -- 본선/지선 구분. 시간표에는 없는 축이다
    src_station_cd      text    NOT NULL,
    dir                 text    NOT NULL CHECK (dir IN ('U','D')),
    dir_raw             text,                      -- '상선'/'하선' 원표기
    day_type            text    NOT NULL CHECK (day_type IN ('weekday','saturday','sunday')),
                                                   -- ★ 시간표와 값 집합이 다르다(위 ⑥)
    slot_min            integer NOT NULL,          -- 30분 슬롯 시작(분). 24:30 = 1470 까지
    congestion          double precision,          -- ★ NULL 허용 — 아래
    reason              text CHECK (reason IN ('terminus_direction','after_last_train','no_train_in_window')),
    grade               text    NOT NULL,
    source              text    NOT NULL,
    source_id           text    NOT NULL,
    data_basis_date     text,
    fetched_at          text    NOT NULL
);
--  ★ congestion 을 NOT NULL 로 잡고 0 을 채우면 안 된다. 0 은 혼잡도 0% 가 아니라
--    '그 방향으로 출발하는 열차가 없다'는 뜻이고, 0 을 값으로 두면 그 구간이
--    **가장 한산한 구간**으로 뒤집힌다. 원인을 reason 에 남긴다.
--    이 성질이 dir 매핑 검증(C1)의 근거이기도 하다(26 조합 중 25 일치).
CREATE UNIQUE INDEX IF NOT EXISTS ux_congestion ON mobility.mob_congestion (src_station_cd, dir_raw, day_type, slot_min);
CREATE INDEX IF NOT EXISTS ix_congestion_lookup ON mobility.mob_congestion (station_key, dir, day_type, slot_min);

-- A6. 서울 시내버스 노선 (21) ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mobility.mob_bus_route (
    route_id            text    PRIMARY KEY,
    route_nm            text    NOT NULL,
    route_type          text,
    route_type_nm       text,
    route_type_grade    text,
    corp_nm             text,
    st_station_nm       text,
    ed_station_nm       text,
    length_km           double precision,
    term_min            integer,                   -- ★ NULL 허용 — 아래
    first_min           integer,                   -- 분 단위
    last_min            integer,                   -- 27:30 = 1650 같은 값이 들어온다
    crosses_midnight    smallint NOT NULL DEFAULT 0 CHECK (crosses_midnight IN (0,1)),
    grade_service_window text,
    grade_wait          text,
    source              text,
    source_id           text,
    fetched_at          text
);
--  ★ term_min 이 NULL 인 것은 배차 0분이 아니라 **배차 개념이 없다**는 뜻이다
--    (예약제·출퇴근 전용). 소스가 0 으로 주는 것을 그대로 넣으면 대기 0분이 되어 "바로 탄다"가 된다.
CREATE INDEX IF NOT EXISTS ix_bus_route_nm ON mobility.mob_bus_route (route_nm);

-- A7. 버스 정류장 (1,397행 · 고유 906 · 좌표 1,027) ──────────────────────
CREATE TABLE IF NOT EXISTS mobility.mob_bus_stop (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id            text    NOT NULL REFERENCES mobility.mob_bus_route(route_id),
    seq                 integer NOT NULL,
    station_id          text    NOT NULL,
    ars_id              text,
    station_nm          text    NOT NULL,
    lat                 double precision,
    lng                 double precision,
    direction           text,
    sect_dist_m         integer,
    transfer_yn         text,
    source              text,
    source_id           text,
    fetched_at          text
);
--  한 정류장이 여러 노선에 나오므로 (route_id, seq) 가 키다. station_id 는 중복된다.
CREATE UNIQUE INDEX IF NOT EXISTS ux_bus_stop ON mobility.mob_bus_stop (route_id, seq);
CREATE INDEX IF NOT EXISTS ix_bus_stop_station ON mobility.mob_bus_stop (station_id);
CREATE INDEX IF NOT EXISTS ix_bus_stop_geo ON mobility.mob_bus_stop (lat, lng);
    --  대안 열거(F3)의 stops_near() 가 좌표로 훑는다.
    --  ※ PG 에는 PostGIS·earthdistance 가 있지만 쓰지 않는다 — 확장 설치가 팀 DB 권한에 걸리고,
    --    906 정류장 규모에서 이 인덱스로 충분하다.

-- A8. 버스 표정속도 ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mobility.mob_bus_speed (
    route_nm            text    PRIMARY KEY,
    route_type_nm       text,
    speed_kmh           double precision,          -- 우리 실측(관측 기반)
    stat_kmh            double precision,          -- 교통카드 통계의 유형값
    by_hour_kmh         jsonb,                     -- ← TEXT(JSON 문자열)에서 바뀐 자리. 시간대별 실측
    observed_km         double precision,
    observed_min        integer,
    grade               text    NOT NULL,
    source_id           text,
    built_at            text
);
--  ★ 인계 목록의 9개에서 하나 늘렸다(담당 결정). 판정기가 버스 승차 소요를 낼 때 읽는
--    참조 데이터이고, 규칙이 아니라 관측값이라 rules json 이 아니라 여기가 맞다.
--  ★ 실측값이 유형값을 덮는다. 같은 순환선인데 01A 15.3 · 01B 17.8 로 갈린다 —
--    유형 단위로는 못 담는 차이다. 그래서 노선 단위로 둔다.

-- A9. 공항 리무진 출발 (8,949) ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mobility.mob_airport_bus_departure (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_no            text    NOT NULL,
    route_key           text    NOT NULL,
    terminal            text    NOT NULL,          -- 'T1' | 'T2'
    dir                 text    NOT NULL,          -- 'from_airport' | 'to_airport'
    day_type            text    NOT NULL,
    dep_min             integer,
    first_min           integer,
    last_min            integer,
    area                text,
    bus_class           text,
    fare_adult          integer,                   -- 운영사 공시 요금. 카카오 유래가 아니다(위 ⑤)
    operator            text,
    ride_location       text,
    timetable_available smallint NOT NULL DEFAULT 0 CHECK (timetable_available IN (0,1)),
    grade               text    NOT NULL,
    source              text    NOT NULL,
    fetched_at          text    NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_airport_bus
    ON mobility.mob_airport_bus_departure (route_no, terminal, dir, day_type, dep_min);

-- A10. 공휴일 (46) ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mobility.mob_holiday (
    holiday_date        text    PRIMARY KEY,       -- 'YYYY-MM-DD' (date 로 안 올린 이유는 이식 규칙 ⓒ)
    name                text,
    source              text,
    fetched_at          text
);
--  day_type_of() 의 정본. 요일축 판정이 여기서 갈린다. 토요일은 holiday 로 본다.


-- ════════════════════════════════════════════════════════════════════════
--  B. 모듈 산출 — 되돌릴 수 없다. 백업 대상.
--     재적재(TRUNCATE)에서 **제외한다.**
-- ════════════════════════════════════════════════════════════════════════

-- B1. 구간 판정 이력 ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mobility.mob_leg_verdict (
    verdict_id          text    PRIMARY KEY,       -- 'mob:{case_id}:{leg_id}:{decided_at}'
    case_id             text    NOT NULL,
    task_id             text,
    run_id              text,
    leg_id              text    NOT NULL,
    schedule_version    integer,
    decided_at          text    NOT NULL,
    verdict             text    NOT NULL CHECK (verdict IN ('ok','fail','unknown','rejected_by_limit')),
                                                   -- 계약 decisions[].verdict 는 ok/fail/unknown 3종.
                                                   -- rejected_by_limit 은 모듈 내부 구분이며
                                                   -- 코어로 낼 때 fail + relax 로 접는다(접기 설계 v1).
    evidence_grade      text    NOT NULL CHECK (evidence_grade IN ('확정','추정','근거없음')),
    from_name           text,
    to_name             text,
    depart_at_min       integer,
    arrive_by_min       integer,
    arrive_est_min      integer,                   -- 도착 예상. 소요를 모르면 NULL('성립 + 도착 미상')
    reasons_json        jsonb,                     -- ← TEXT 에서 바뀐 자리. JSON 배열
    relax_json          jsonb,                     -- ← 〃  완화 조건
    estimate_json       jsonb,                     -- ← 〃  duration_min·transfers·grade 등
    stage_assumed       smallint NOT NULL DEFAULT 0 CHECK (stage_assumed IN (0,1)),
    rules_version       text,                      -- 'rules_v0.3'
    timetable_built_at  text                       -- 어느 판 시간표로 냈는지
);
--  ★ 참조 데이터로 FK 를 걸지 않는다(일부러 · 위 ⑦). 시간표는 개정 때 통째로 교체되므로
--    FK 를 걸면 재적재마다 지난 판정이 깨진다. 판정 이력은 그 시점의 사실이고
--    참조 데이터의 현재 상태와 무관하게 남아야 한다.
--    대신 timetable_built_at 으로 "어느 판을 보고 낸 판정인지"를 남긴다.
--    ★★ PG 로 옮기면서 이 결정이 더 중요해졌다 — 참조 표 재적재를 TRUNCATE 로 하는데,
--       FK 가 걸려 있으면 TRUNCATE 가 CASCADE 를 요구하거나 거부된다.
--  ★ 재확인(F2)이 이 표를 읽어 "지난번과 달라졌나"를 비교한다. 이력이 없으면 F2 가 성립하지 않는다.
CREATE INDEX IF NOT EXISTS ix_verdict_case ON mobility.mob_leg_verdict (case_id, leg_id, decided_at DESC);

-- B2. 판정 근거 ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mobility.mob_verdict_evidence (
    verdict_id          text    NOT NULL REFERENCES mobility.mob_leg_verdict(verdict_id) ON DELETE CASCADE,
    evidence_id         text    NOT NULL,          -- 'mob:{leg_id}:{kind}:{n}' — ★ 한 결과 안에서만 유일하다
    source_type         text    NOT NULL CHECK (source_type IN ('db','policy','case_event')),
    source_id           text    NOT NULL,          -- 'tago_subway@2026-09-09' · 'mobility_rules@v0.3'
    claim               text    NOT NULL,
    value_json          jsonb,                     -- ← TEXT 에서 바뀐 자리
    confidence          double precision CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    observed_at         text    NOT NULL,          -- 시간표는 수집일, 규칙은 개정일 (위 ⓒ)
    PRIMARY KEY (verdict_id, evidence_id)
);
--  ★ PK 가 복합키인 이유(2026-09-13). evidence_id 'mob:L3:timetable:1' 은 **Case 가 달라도 같은 문자열**이다.
--    단독 PK 로 두면 두 번째 Case 의 적재가 PK 충돌로 터진다. evidence_id 는 한 결과(TeamResult) 안에서만
--    유일하면 되고, 길게 만들면 answer·evidence 예산에 불리하다.
--    ※ SQLite 판에서는 패치(mobility_evidence_pk_patch_20260913.sql)로 고쳤다. 이 이식본은 처음부터 복합키다.
--  ★ value_json 은 mobility_scripts/mobility_checks/contract/mob_evidence_value_v1.schema.json 로 검증한 뒤 적재한다.
--    저장하는 kind 는 timetable·rule·walk·bus·issue·prev_verdict 여섯. verdict·run·alt 는 저장하지 않고
--    mob_leg_verdict 행에서 접을 때 생성한다(접기 설계 v1 §15).
--    ※ PG 에는 JSON Schema 제약이 없다. 검증은 적재기가 계속 한다 — jsonb 로 바뀌었다고 검증이 생기지 않는다.
--      jsonb 로 얻는 것은 (1) 잘못된 JSON 문자열이 아예 안 들어간다 (2) 질의로 안을 들여다볼 수 있다 두 가지다.
--  ★★ source_type 의 CHECK 가 이 스키마에서 가장 중요한 한 줄이다.
--     계약의 Evidence.source_type 은 6종이지만 우리는 셋만 허용한다.
--     빠진 셋 중 **'tool_result' 가 카카오 응답**이고, 2026-09-09 약관 확인에서
--     원값·가공값 모두 저장 금지로 정리됐다. 문서로만 두면 언젠가 누가 넣는다.
--     'customer_message'·'remote_agent' 는 이 모듈이 만들 일이 없다.
--     ※ 새 source_type 이 필요하면 넓히기 전에 02·04번 방과 합의할 것.
--       2026-09-11 에 이슈 근거를 'external' 로 냈다가 적재에서 통째로 거부된 적이 있다.
--       판정은 맞는데 근거만 사라지는 가장 나쁜 형태였다 → 'case_event' 로 정리했다.
--  ★ 근거 등급 '근거없음'은 Evidence 를 만들지 않는다. "없다"를 Evidence 로 만들면 근거 대조에서 확정과 섞인다.
--    mob_leg_verdict.evidence_grade='근거없음' + reasons_json 으로 남긴다.
CREATE INDEX IF NOT EXISTS ix_evidence_verdict ON mobility.mob_verdict_evidence (verdict_id);


-- ════════════════════════════════════════════════════════════════════════
--  C. 적재 메타 — 어느 판으로 채웠는지
-- ════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS mobility.mob_load_meta (
    table_name          text    PRIMARY KEY,
    row_count           integer NOT NULL,
    src_file            text,
    src_built_at        text,
    loaded_at           text    NOT NULL
);


-- ════════════════════════════════════════════════════════════════════════
--  D. 주석을 DB 안에 남긴다 — .sql 파일을 안 보고 \d+ 로만 보는 사람을 위해
--     원본 SQLite 에는 없던 자리다. 여기 올린 것은 **되돌리면 버그가 돌아오는 다섯 줄**만이다.
-- ════════════════════════════════════════════════════════════════════════
COMMENT ON COLUMN mobility.mob_timetable.dep_min IS
  '분 단위. 24시 이상 가능(1490=24:50). NULL 은 "출발 없음"(시·종착역)이며 0/24 로 채우면 막차 판정이 뒤집힌다.';
COMMENT ON COLUMN mobility.mob_timetable.dir IS
  '소스가 준 값. 방향의 정본이 아니다 — 인천2호선·신림선은 같은 dir 에 양 끝 행선지가 섞인다. 판정은 dest_station_nm + mob_line_edge 로 한다.';
COMMENT ON COLUMN mobility.mob_congestion.congestion IS
  'NULL 허용. 0 은 혼잡도 0%% 가 아니라 "그 방향 열차가 없다"는 뜻이고, 0 으로 채우면 가장 한산한 구간으로 뒤집힌다. 원인은 reason 에.';
COMMENT ON COLUMN mobility.mob_bus_route.term_min IS
  'NULL 은 배차 0분이 아니라 "배차 개념이 없다"(예약제·출퇴근 전용). 0 으로 채우면 대기 0분이 되어 "바로 탄다"가 된다.';
COMMENT ON COLUMN mobility.mob_verdict_evidence.source_type IS
  '계약은 6종이지만 셋만 허용한다. tool_result(경로 API 응답)를 스키마로 막는 자리다 — 약관 방침을 문서가 아니라 제약으로 강제한다. 넓히기 전 02·04번 방과 합의할 것.';
COMMENT ON TABLE mobility.mob_leg_verdict IS
  '모듈 산출 · 되돌릴 수 없다. 참조 표 재적재(TRUNCATE) 대상이 아니다. 참조 데이터로 FK 를 일부러 걸지 않는다.';
COMMENT ON SCHEMA mobility IS
  '이동·동선 모듈 저장소. 참조 10표(재생성 가능) + 산출 2표(백업 대상) + 적재 메타 1표.';


-- ════════════════════════════════════════════════════════════════════════
--  E. 전환 뒤 확인 — 적재가 끝나면 이 질의로 SQLite 판과 대조한다
-- ════════════════════════════════════════════════════════════════════════
-- SELECT 'mob_timetable' t, count(*) FROM mobility.mob_timetable           -- 기대 463,326
-- UNION ALL SELECT 'mob_congestion',    count(*) FROM mobility.mob_congestion          -- 65,169
-- UNION ALL SELECT 'mob_airport_bus',   count(*) FROM mobility.mob_airport_bus_departure --  8,949
-- UNION ALL SELECT 'mob_bus_stop',      count(*) FROM mobility.mob_bus_stop            --  1,397
-- UNION ALL SELECT 'mob_station_coord', count(*) FROM mobility.mob_station_coord       --    793
-- UNION ALL SELECT 'mob_line_edge',     count(*) FROM mobility.mob_line_edge           --    777
-- UNION ALL SELECT 'mob_transfer_walk', count(*) FROM mobility.mob_transfer_walk       --    213
-- UNION ALL SELECT 'mob_holiday',       count(*) FROM mobility.mob_holiday             --     46
-- UNION ALL SELECT 'mob_bus_route',     count(*) FROM mobility.mob_bus_route           --     21
-- UNION ALL SELECT 'mob_bus_speed',     count(*) FROM mobility.mob_bus_speed;          --      2
--
-- ★ 행수만 맞으면 안 된다. 적재 후 점검 11가지(load_mobility_db.py)를 그대로 돌린다.
--   그중 "있어야 정상인 것"도 센다 — 24시 이상 dep_min, NULL 출발 2,527행.
--   그 수가 0 이 되면 정규화가 조용히 되돌아간 것이다.
